const router=require("express").Router(); const Story=require("../models/Story"); const auth=require("../middleware/auth");
router.get("/",auth,async(req,res)=>{const stories=await Story.find({expiresAt:{$gt:new Date()}}).populate("author","name username profileImage").populate("viewers","name username profileImage").populate("comments.author","name username profileImage").sort({createdAt:-1});res.json({stories:stories.map(story=>{const item=story.toObject();item.viewerCount=item.viewers.length;if(String(story.author._id)!==req.user.userId)delete item.viewers;return item;})})});
router.post("/",auth,async(req,res)=>{if(!req.body.media?.url)return res.status(400).json({message:'Story media is required'});const story=await Story.create({author:req.user.userId,media:req.body.media,caption:String(req.body.caption||'').trim()});res.status(201).json({story})});
router.patch("/:id",auth,async(req,res)=>{const story=await Story.findById(req.params.id);if(!story)return res.status(404).json({message:'Story not found'});if(story.author.toString()!==req.user.userId)return res.status(403).json({message:'You can only edit your own story'});story.caption=String(req.body.caption||'').trim();await story.save();res.json({story})});
router.delete("/:id",auth,async(req,res)=>{const story=await Story.findById(req.params.id);if(!story)return res.status(404).json({message:'Story not found'});if(story.author.toString()!==req.user.userId)return res.status(403).json({message:'You can only delete your own story'});await story.deleteOne();res.status(204).end()});
router.post("/:id/view",auth,async(req,res)=>{const story=await Story.findOneAndUpdate({_id:req.params.id,author:{$ne:req.user.userId}},{$addToSet:{viewers:req.user.userId}},{new:true});if(!story)return res.status(404).json({message:'Story not found'});res.json({viewerCount:story.viewers.length})});
router.post("/:id/like",auth,async(req,res)=>{const story=await Story.findById(req.params.id);if(!story)return res.status(404).json({message:'Story not found'});const exists=story.likes.some(id=>String(id)===req.user.userId);story.likes=exists?story.likes.filter(id=>String(id)!==req.user.userId):[...story.likes,req.user.userId];await story.save();res.json({liked:!exists,likes:story.likes.length})});
router.post("/:id/comments",auth,async(req,res)=>{const story=await Story.findById(req.params.id);const text=String(req.body.text||'').trim();if(!story)return res.status(404).json({message:'Story not found'});if(!text)return res.status(400).json({message:'Comment cannot be empty'});story.comments.push({author:req.user.userId,text});await story.save();await story.populate('comments.author','name username profileImage');res.status(201).json({comment:story.comments.at(-1)})});
module.exports=router;
